/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/alauda/kube-ovn/pkg/apis/kubeovn/v1"
	scheme "github.com/alauda/kube-ovn/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SfcsGetter has a method to return a SfcInterface.
// A group's client should implement this interface.
type SfcsGetter interface {
	Sfcs() SfcInterface
}

// SfcInterface has methods to work with Sfc resources.
type SfcInterface interface {
	Create(*v1.Sfc) (*v1.Sfc, error)
	Update(*v1.Sfc) (*v1.Sfc, error)
	UpdateStatus(*v1.Sfc) (*v1.Sfc, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Sfc, error)
	List(opts metav1.ListOptions) (*v1.SfcList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Sfc, err error)
	SfcExpansion
}

// sfcs implements SfcInterface
type sfcs struct {
	client rest.Interface
}

// newSfcs returns a Sfcs
func newSfcs(c *KubeovnV1Client) *sfcs {
	return &sfcs{
		client: c.RESTClient(),
	}
}

// Get takes name of the sfc, and returns the corresponding sfc object, and an error if there is any.
func (c *sfcs) Get(name string, options metav1.GetOptions) (result *v1.Sfc, err error) {
	result = &v1.Sfc{}
	err = c.client.Get().
		Resource("sfcs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Sfcs that match those selectors.
func (c *sfcs) List(opts metav1.ListOptions) (result *v1.SfcList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SfcList{}
	err = c.client.Get().
		Resource("sfcs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sfcs.
func (c *sfcs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("sfcs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a sfc and creates it.  Returns the server's representation of the sfc, and an error, if there is any.
func (c *sfcs) Create(sfc *v1.Sfc) (result *v1.Sfc, err error) {
	result = &v1.Sfc{}
	err = c.client.Post().
		Resource("sfcs").
		Body(sfc).
		Do().
		Into(result)
	return
}

// Update takes the representation of a sfc and updates it. Returns the server's representation of the sfc, and an error, if there is any.
func (c *sfcs) Update(sfc *v1.Sfc) (result *v1.Sfc, err error) {
	result = &v1.Sfc{}
	err = c.client.Put().
		Resource("sfcs").
		Name(sfc.Name).
		Body(sfc).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *sfcs) UpdateStatus(sfc *v1.Sfc) (result *v1.Sfc, err error) {
	result = &v1.Sfc{}
	err = c.client.Put().
		Resource("sfcs").
		Name(sfc.Name).
		SubResource("status").
		Body(sfc).
		Do().
		Into(result)
	return
}

// Delete takes name of the sfc and deletes it. Returns an error if one occurs.
func (c *sfcs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("sfcs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sfcs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("sfcs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched sfc.
func (c *sfcs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Sfc, err error) {
	result = &v1.Sfc{}
	err = c.client.Patch(pt).
		Resource("sfcs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
