/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/alauda/kube-ovn/pkg/apis/kubeovn/v1"
	scheme "github.com/alauda/kube-ovn/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VnfGroupsGetter has a method to return a VnfGroupInterface.
// A group's client should implement this interface.
type VnfGroupsGetter interface {
	VnfGroups() VnfGroupInterface
}

// VnfGroupInterface has methods to work with VnfGroup resources.
type VnfGroupInterface interface {
	Create(*v1.VnfGroup) (*v1.VnfGroup, error)
	Update(*v1.VnfGroup) (*v1.VnfGroup, error)
	UpdateStatus(*v1.VnfGroup) (*v1.VnfGroup, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.VnfGroup, error)
	List(opts metav1.ListOptions) (*v1.VnfGroupList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.VnfGroup, err error)
	VnfGroupExpansion
}

// vnfGroups implements VnfGroupInterface
type vnfGroups struct {
	client rest.Interface
}

// newVnfGroups returns a VnfGroups
func newVnfGroups(c *KubeovnV1Client) *vnfGroups {
	return &vnfGroups{
		client: c.RESTClient(),
	}
}

// Get takes name of the vnfGroup, and returns the corresponding vnfGroup object, and an error if there is any.
func (c *vnfGroups) Get(name string, options metav1.GetOptions) (result *v1.VnfGroup, err error) {
	result = &v1.VnfGroup{}
	err = c.client.Get().
		Resource("vnfgroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VnfGroups that match those selectors.
func (c *vnfGroups) List(opts metav1.ListOptions) (result *v1.VnfGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.VnfGroupList{}
	err = c.client.Get().
		Resource("vnfgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vnfGroups.
func (c *vnfGroups) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("vnfgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a vnfGroup and creates it.  Returns the server's representation of the vnfGroup, and an error, if there is any.
func (c *vnfGroups) Create(vnfGroup *v1.VnfGroup) (result *v1.VnfGroup, err error) {
	result = &v1.VnfGroup{}
	err = c.client.Post().
		Resource("vnfgroups").
		Body(vnfGroup).
		Do().
		Into(result)
	return
}

// Update takes the representation of a vnfGroup and updates it. Returns the server's representation of the vnfGroup, and an error, if there is any.
func (c *vnfGroups) Update(vnfGroup *v1.VnfGroup) (result *v1.VnfGroup, err error) {
	result = &v1.VnfGroup{}
	err = c.client.Put().
		Resource("vnfgroups").
		Name(vnfGroup.Name).
		Body(vnfGroup).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *vnfGroups) UpdateStatus(vnfGroup *v1.VnfGroup) (result *v1.VnfGroup, err error) {
	result = &v1.VnfGroup{}
	err = c.client.Put().
		Resource("vnfgroups").
		Name(vnfGroup.Name).
		SubResource("status").
		Body(vnfGroup).
		Do().
		Into(result)
	return
}

// Delete takes name of the vnfGroup and deletes it. Returns an error if one occurs.
func (c *vnfGroups) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("vnfgroups").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vnfGroups) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("vnfgroups").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched vnfGroup.
func (c *vnfGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.VnfGroup, err error) {
	result = &v1.VnfGroup{}
	err = c.client.Patch(pt).
		Resource("vnfgroups").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
