/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	kubeovnv1 "github.com/alauda/kube-ovn/pkg/apis/kubeovn/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSfcs implements SfcInterface
type FakeSfcs struct {
	Fake *FakeKubeovnV1
}

var sfcsResource = schema.GroupVersionResource{Group: "kubeovn.io", Version: "v1", Resource: "sfcs"}

var sfcsKind = schema.GroupVersionKind{Group: "kubeovn.io", Version: "v1", Kind: "Sfc"}

// Get takes name of the sfc, and returns the corresponding sfc object, and an error if there is any.
func (c *FakeSfcs) Get(name string, options v1.GetOptions) (result *kubeovnv1.Sfc, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(sfcsResource, name), &kubeovnv1.Sfc{})
	if obj == nil {
		return nil, err
	}
	return obj.(*kubeovnv1.Sfc), err
}

// List takes label and field selectors, and returns the list of Sfcs that match those selectors.
func (c *FakeSfcs) List(opts v1.ListOptions) (result *kubeovnv1.SfcList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(sfcsResource, sfcsKind, opts), &kubeovnv1.SfcList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &kubeovnv1.SfcList{ListMeta: obj.(*kubeovnv1.SfcList).ListMeta}
	for _, item := range obj.(*kubeovnv1.SfcList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sfcs.
func (c *FakeSfcs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(sfcsResource, opts))
}

// Create takes the representation of a sfc and creates it.  Returns the server's representation of the sfc, and an error, if there is any.
func (c *FakeSfcs) Create(sfc *kubeovnv1.Sfc) (result *kubeovnv1.Sfc, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(sfcsResource, sfc), &kubeovnv1.Sfc{})
	if obj == nil {
		return nil, err
	}
	return obj.(*kubeovnv1.Sfc), err
}

// Update takes the representation of a sfc and updates it. Returns the server's representation of the sfc, and an error, if there is any.
func (c *FakeSfcs) Update(sfc *kubeovnv1.Sfc) (result *kubeovnv1.Sfc, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(sfcsResource, sfc), &kubeovnv1.Sfc{})
	if obj == nil {
		return nil, err
	}
	return obj.(*kubeovnv1.Sfc), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSfcs) UpdateStatus(sfc *kubeovnv1.Sfc) (*kubeovnv1.Sfc, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(sfcsResource, "status", sfc), &kubeovnv1.Sfc{})
	if obj == nil {
		return nil, err
	}
	return obj.(*kubeovnv1.Sfc), err
}

// Delete takes name of the sfc and deletes it. Returns an error if one occurs.
func (c *FakeSfcs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(sfcsResource, name), &kubeovnv1.Sfc{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSfcs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(sfcsResource, listOptions)

	_, err := c.Fake.Invokes(action, &kubeovnv1.SfcList{})
	return err
}

// Patch applies the patch and returns the patched sfc.
func (c *FakeSfcs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *kubeovnv1.Sfc, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(sfcsResource, name, pt, data, subresources...), &kubeovnv1.Sfc{})
	if obj == nil {
		return nil, err
	}
	return obj.(*kubeovnv1.Sfc), err
}
